apiVersion: apps/v1
kind: Deployment
metadata:
  name: sysdig-admission-controller
  namespace: sysdig-shield
spec:
  template:
    spec:
      containers:
      - name: admission-controller
        resources:
          requests:
            cpu: 150m
            memory: 192Mi
          limits:
            cpu: 400m
            memory: 384Mi
