apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sysdig-node-analyzer
  namespace: sysdig-shield
spec:
  template:
    spec:
      containers:
      - name: node-analyzer
        resources:
          requests:
            cpu: 150m
            memory: 192Mi
          limits:
            cpu: 400m
            memory: 384Mi
