apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sysdig-agent
  namespace: sysdig-shield
spec:
  template:
    spec:
      containers:
      - name: sysdig-agent
        resources:
          requests:
            cpu: 300m
            memory: 384Mi
          limits:
            cpu: 750m
            memory: 768Mi
