---
# SecretStore for HashiCorp Vault
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault
  namespace: sysdig-shield
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  provider:
    vault:
      server: "https://vault.example.com:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "sysdig-shield"
          serviceAccountRef:
            name: sysdig-agent
---
# ExternalSecret using Vault
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sysdig-agent-vault
  namespace: sysdig-shield
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  secretStoreRef:
    name: vault
    kind: SecretStore
  target:
    name: sysdig-agent
    creationPolicy: Owner
  refreshInterval: 1h
  data:
  - secretKey: access-key
    remoteRef:
      key: sysdig/shield
      property: access-key
---
# ClusterSecretStore for Vault (cluster-wide)
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  provider:
    vault:
      server: "https://vault.example.com:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets"
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets-system
