# cert-manager Certificate for Admission Controller Webhook
#
# Prerequisites:
# 1. Install cert-manager in your cluster
# 2. Create a ClusterIssuer or Issuer (self-signed for testing, Let's Encrypt for production)
#
# cert-manager will automatically:
# - Generate a private key
# - Create a certificate signing request
# - Sign the certificate
# - Store tls.crt and tls.key in the specified Secret
# - Rotate the certificate before expiration

---
# Self-signed ClusterIssuer (for testing/dev)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  selfSigned: {}

---
# CA Issuer (recommended for production)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-issuer
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  ca:
    secretName: ca-key-pair

---
# Certificate for Admission Controller Webhook
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sysdig-admission-controller-tls
  namespace: sysdig-shield
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  # Secret name where cert-manager will store tls.crt and tls.key
  secretName: sysdig-admission-controller-tls

  # Certificate duration (90 days)
  duration: 2160h

  # Renew 30 days before expiration
  renewBefore: 720h

  # Subject
  subject:
    organizations:
    - sysdig-shield

  # Common Name
  commonName: sysdig-admission-controller.sysdig-shield.svc

  # DNS names (MUST match webhook service)
  dnsNames:
  - sysdig-admission-controller
  - sysdig-admission-controller.sysdig-shield
  - sysdig-admission-controller.sysdig-shield.svc
  - sysdig-admission-controller.sysdig-shield.svc.cluster.local

  # Issuer reference (use selfsigned-issuer for testing, ca-issuer for production)
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io

  # Private key configuration
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048

  # Usage
  usages:
  - digital signature
  - key encipherment
  - server auth

---
# Alternative: Certificate with custom CA
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sysdig-admission-controller-tls-ca
  namespace: sysdig-shield
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  secretName: sysdig-admission-controller-tls
  duration: 8760h  # 1 year
  renewBefore: 1440h  # 60 days
  subject:
    organizations:
    - sysdig-shield
  commonName: sysdig-admission-controller.sysdig-shield.svc
  dnsNames:
  - sysdig-admission-controller.sysdig-shield.svc
  - sysdig-admission-controller.sysdig-shield.svc.cluster.local
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  privateKey:
    algorithm: RSA
    size: 4096
  usages:
  - digital signature
  - key encipherment
  - server auth

---
# Verify certificate after creation:
# kubectl get certificate -n sysdig-shield
# kubectl describe certificate sysdig-admission-controller-tls -n sysdig-shield
# kubectl get secret sysdig-admission-controller-tls -n sysdig-shield -o yaml
