# Sealed Secret Example for Sysdig Agent
#
# To create a sealed secret:
# 1. Create a regular secret (DO NOT apply to cluster):
#    kubectl create secret generic sysdig-agent \
#      --from-literal=access-key=YOUR_SYSDIG_ACCESS_KEY \
#      --namespace=sysdig-shield \
#      --dry-run=client -o yaml > sysdig-agent-secret.yaml
#
# 2. Seal the secret using kubeseal:
#    kubeseal --format yaml < sysdig-agent-secret.yaml > sysdig-agent-sealed.yaml
#
# 3. Commit the sealed secret to Git:
#    git add sysdig-agent-sealed.yaml
#    git commit -m "Add sealed Sysdig access key"
#
# 4. Delete the plaintext secret file:
#    rm sysdig-agent-secret.yaml
#
# The sealed-secrets controller will decrypt and create the Secret in the cluster.

---
# Example SealedSecret structure (this is NOT a real encrypted secret)
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sysdig-agent
  namespace: sysdig-shield
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    sealedsecrets.bitnami.com/cluster-wide: "false"
spec:
  encryptedData:
    # This is a placeholder - use kubeseal to generate real encrypted data
    access-key: AgA7Y... (encrypted value here)
  template:
    metadata:
      name: sysdig-agent
      namespace: sysdig-shield
    type: Opaque

---
# Example SealedSecret for Admission Controller TLS
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sysdig-admission-controller-tls
  namespace: sysdig-shield
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  encryptedData:
    # Use kubeseal to encrypt tls.crt and tls.key
    tls.crt: AgB3X... (encrypted certificate)
    tls.key: AgC9Z... (encrypted private key)
  template:
    metadata:
      name: sysdig-admission-controller-tls
      namespace: sysdig-shield
    type: kubernetes.io/tls

---
# Instructions for sealing TLS secrets:
# kubectl create secret tls sysdig-admission-controller-tls \
#   --cert=admission-controller.crt \
#   --key=admission-controller.key \
#   --namespace=sysdig-shield \
#   --dry-run=client -o yaml | \
#   kubeseal --format yaml > sysdig-admission-controller-tls-sealed.yaml
