# ArgoCD Vault Plugin - Secret with Placeholders
#
# Configure ArgoCD to use the Vault plugin:
# 1. Install argocd-vault-plugin in ArgoCD repo server
# 2. Configure Vault authentication in ArgoCD
# 3. Use placeholders in format: <path:secret/path#key>
#
# ArgoCD will replace placeholders with actual values from Vault during sync.

---
# Sysdig Agent Secret with Vault placeholders
apiVersion: v1
kind: Secret
metadata:
  name: sysdig-agent
  namespace: sysdig-shield
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    avp.kubernetes.io/path: "secret/data/sysdig/shield"
type: Opaque
stringData:
  # Vault placeholder - will be replaced by ArgoCD Vault Plugin
  access-key: <access-key>

---
# Alternative format with explicit path in placeholder
apiVersion: v1
kind: Secret
metadata:
  name: sysdig-agent-explicit
  namespace: sysdig-shield
  annotations:
    argocd.argoproj.io/sync-wave: "2"
type: Opaque
stringData:
  # Full path in placeholder
  access-key: <path:secret/data/sysdig/shield#access-key>

---
# Admission Controller TLS with Vault placeholders
apiVersion: v1
kind: Secret
metadata:
  name: sysdig-admission-controller-tls
  namespace: sysdig-shield
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    avp.kubernetes.io/path: "secret/data/sysdig/shield/tls"
type: kubernetes.io/tls
stringData:
  tls.crt: <tls.crt>
  tls.key: <tls.key>

---
# Example Vault KV structure:
#
# secret/data/sysdig/shield:
#   access-key: "your-sysdig-access-key-uuid"
#
# secret/data/sysdig/shield/tls:
#   tls.crt: "-----BEGIN CERTIFICATE-----\n..."
#   tls.key: "-----BEGIN PRIVATE KEY-----\n..."
#
# To write secrets to Vault:
# vault kv put secret/sysdig/shield access-key="YOUR_KEY"
# vault kv put secret/sysdig/shield/tls tls.crt=@admission-controller.crt tls.key=@admission-controller.key

---
# ArgoCD Application configuration for Vault Plugin
# Add this to your ArgoCD Application manifest:
#
# spec:
#   source:
#     plugin:
#       name: argocd-vault-plugin
#       env:
#       - name: AVP_TYPE
#         value: vault
#       - name: AVP_AUTH_TYPE
#         value: k8s
#       - name: AVP_K8S_ROLE
#         value: argocd
