apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sysdig-node-analyzer
  namespace: sysdig-shield
spec:
  template:
    spec:
      containers:
      - name: node-analyzer
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
