apiVersion: apps/v1
kind: Deployment
metadata:
  name: sysdig-admission-controller
  namespace: sysdig-shield
spec:
  template:
    spec:
      containers:
      - name: admission-controller
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi
