apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sysdig-node-analyzer
  namespace: sysdig-shield
spec:
  template:
    spec:
      containers:
      - name: node-analyzer
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi
